### ISSUE TITLE
change backbone

### ISSUE THREAD

**Issue by halyusuf25** [lyuwenyu/RT-DETR#488]
Hi

Is there a way or example of using a backbone other than ResNet? lets say for example EffientNet backbone or anything else. 

Regards
Husain

**Comment by AntonioConsiglio** [comment]
Hello @halyusuf25 I've trained the architecture using the STDC backbone. 

Here’s how you can integrate a custom backbone into the model configuration.

- Add Backbone Implementation
First, add your backbone implementation file in the following folder:

```bash
RT-DETR/rtdetrv2_pytorch/src/nn/backbone
```
- Modify Backbone File
In your backbone file, ensure you have the following:

```python
from ...core import register
__all__ = ['<YourBackboneClassName>']

@register()
class <YourBackboneClassName>():
    ...
```
Replace <YourBackboneClassName> with the actual name of your backbone class.

- Create Configuration File
In the include folder, copy an existing YAML configuration file and modify the backbone-related parts:

```bash
RT-DETR/rtdetrv2_pytorch/configs/rtdetrv2/include
```
Update the YAML file as follows:

```yaml

RTDETR: 
  backbone: <YourBackboneClassName>
  encoder: HybridEncoder
  decoder: RTDETRTransformerv2

<YourBackboneClassName>:
  # Configuration specific to your backbone

HybridEncoder:
  in_channels: [list of output channels from your backbone]
```

- Update Training Configuration
Finally, in one of the configuration files used for training, make sure to link to the updated include YAML file you created.
